<input type="hidden" id="first_name_required" value="@lang('index.first_name_required')">
<input type="hidden" id="last_name_required" value="@lang('index.last_name_required')">
<input type="hidden" id="email_required" value="@lang('index.email_required')">
<input type="hidden" id="are_you_sure" value="@lang('index.are_you_sure')">
<input type="hidden" id="warning" value="@lang('index.warning')">
<input type="hidden" id="ok" value="@lang('index.ok')">
<input type="hidden" id="cancel_text" value="@lang('index.cancel')">
<input type="hidden" id="cannot_revert" value="@lang('index.cannot_revert')">
<input type="hidden" id="title_max_50" value="@lang('index.title_max_50')">
<input type="hidden" id="title_max_250" value="@lang('index.title_max_250')">
<input type="hidden" id="first_name_max_191" value="@lang('index.first_name_max_191')">
<input type="hidden" id="last_name_max_191" value="@lang('index.last_name_max_191')">
<input type="hidden" id="email_max_50" value="@lang('index.email_max_50')">
<input type="hidden" id="invalid_email" value="@lang('index.invalid_email')">
<input type="hidden" id="sure_to_reopen" value="@lang('index.sure_to_reopen')">
<input type="hidden" id="sure_to_close" value="@lang('index.sure_to_close')">
<input type="hidden" id="note_field_required" value="@lang('index.note_field_required')">
<input type="hidden" id="update" value="@lang('index.update')">
<input type="hidden" id="custom_field_type_required" value="@lang('index.custom_field_type_required')">
<input type="hidden" id="label_field_required" value="@lang('index.label_field_required')">
<input type="hidden" id="option_required" value="@lang('index.option_required')">
<input type="hidden" id="lan_title" value="@lang('index.title')">
<input type="hidden" id="confirm_delete_all_notification" value="@lang('index.confirm_delete_all_notification')">
<input type="hidden" id="yes_delete_it" value="@lang('index.yes_delete_it')">
<input type="hidden" id="no_article_group_found" value="@lang('index.no_article_group_found')">
<input type="hidden" id="no_article_found" value="@lang('index.no_article_found')">
<input type="hidden" id="save_message" value="@lang('index.save_message')">
<input type="hidden" id="update_message" value="@lang('index.update_message')">
<input type="hidden" id="delete_message" value="@lang('index.delete_message')">
<input type="hidden" id="email_already_registered" value="@lang('index.email.unique')">
<input type="hidden" id="mobile_already_registered" value="@lang('index.mobile.unique')">
<input type="hidden" id="sure_to_archive" value="@lang('index.sure_to_archive')">
<input type="hidden" id="send_payment_request" value="@lang('index.send_payment_request')">
<input type="hidden" id="no_data_found" value="@lang('index.no_data_found')">
<input type="hidden" id="is_submit" value="@lang('index.submit')">
<input type="hidden" id="please_wait" value="@lang('index.please_wait')">
<input type="hidden" id="reply_and_close" value="@lang('index.reply_and_close')">
<input type="hidden" id="reply_text" value="@lang('index.replay')">
<input type="hidden" id="file_size_required" value="@lang('index.file_size_required')">
<input type="hidden" id="file_size_required_1" value="@lang('index.file_size_required_1')">
<input type="hidden" id="file_size_required_2" value="@lang('index.file_size_required_2')">
<input type="hidden" id="file_size_required_3" value="@lang('index.file_size_required_3')">
<input type="hidden" id="file_size_required_4" value="@lang('index.file_size_required_4')">
<input type="hidden" id="file_size_required_5" value="@lang('index.file_size_required_5')">
<input type="hidden" id="file_size_required_6" value="@lang('index.file_size_required_6')">
<input type="hidden" id="file_size_required_7" value="@lang('index.file_size_required_7')">
<input type="hidden" id="please_add_at_least_1_field" value="@lang('index.please_add_at_least_1_field')">
<input type="hidden" id="str_Print" value="@lang('index.Print')">
<input type="hidden" id="str_Copy" value="@lang('index.Copy')">
<input type="hidden" id="str_Excel" value="@lang('index.Excel')">
<input type="hidden" id="str_CSV" value="@lang('index.CSV')">
<input type="hidden" id="str_PDF" value="@lang('index.PDF')">
<input type="hidden" id="str_Previous" value="@lang('index.Previous')">
<input type="hidden" id="str_Next" value="@lang('index.Next')">
<input type="hidden" id="please_login" value="@lang('index.please_login')">
